CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_NAME TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);

INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_NAME,CATEGORY_ID,UNIT,PRICE) VALUES
    ('1','NOTEBOOK','AADHYA','13','20-BOXES',20),
    ('2','PENS','AADHYA','21','10-BOXES',15),
    ('3','PAINTING-KIT','ALOK','47','35-BOXES',150),
    ('4','A4-PAPER','RUDRAKSH','29','80-PACKS',50),
    ('5','MARKERS','ALOK','33','15-BOXES',30),
    ('6','CHART-PAPER','RUDRAKSH','69','90-ROLLS',50);

SELECT DISTINCT(SUPPLIER_NAME) AS NAMES FROM PRODUCT;
SELECT COUNT(PRODUCT_NAME) AS COUNT FROM PRODUCT;
SELECT COUNT(DISTINCT(SUPPLIER_NAME)) AS SUPPLIERS FROM PRODUCT;
SELECT SUM(PRICE) AS TOTAL_PRICE FROM PRODUCT;
SELECT AVG(PRICE) AS AVG_PRICE FROM PRODUCT;