CREATE TABLE IF NOT EXISTS nomnom (
    NAME TEXT, 
    NEIGHBOURHOOD TEXT, 
    CUISINE TEXT, 
    REVIEW REAL, 
    PRICE TEXT, 
    HEALTH TEXT
); 
INSERT INTO nomnom (NAME, NEIGHBOURHOOD, CUISINE, REVIEW, PRICE, HEALTH)VALUES
    ('Peter', 'Brooklyn', 'Steak', 4.4, '$$$$', 'A'),
    ('Jongro', 'Midtown', 'Korean', 3.5, '$$', 'A'), 
    ('Pocha', 'Midtown', 'Pizza', 4, '$$$', 'B'),
    ('Lighthouse', 'Queens', 'Chinese', 3.9, '$', 'A'), 
    ('Minca', 'Downtown', 'American', 4.6, '$$$', ''), 
    ('Marea', 'Chinatown', 'Chinese', 3.0, '$$', ''),
    ('Dirty Candy', 'Uptown', 'Italian', 4.9, '$$$$', 'B'), 
    ('Di Fara Pizza', 'Brooklyn', 'Pizza', 3.8, '$$$', 'A'), 
    ('Golden Unicorn', 'Uptown', 'Italian', 3.8, '$$', 'A');
SELECT * FROM NOMNOM;

-- SELECT DISTINCT NEIGHBOURHOODS 
SELECT DISTINCT(NEIGHBOURHOOD) FROM NOMNOM ;

-- SELECT UNIQUE CUISINE
SELECT DISTINCT(CUISINE) FROM NOMNOM;

-- SELECT ALL THE RECORDS WITH CHINESE CUISINE
SELECT * FROM NOMNOM WHERE CUISINE='Chinese';

-- SELECT ALL THE RECORDS WHERE REVIEW RATING IS 4 OR GREATER
SELECT * FROM NOMNOM WHERE REVIEW >= 4;

-- NO. OF REVIEWS GREATER THAN EQUALS TO 4
--SELECT COUNT(*) AS TOTAL COUNT FROM NOMNOM WHERE REVIEW>=4;

-- SELECT ALL THE RECORDS WHERE CUISINE IS ITALIAN AND PRICE IS $$$
SELECT * FROM NOMNOM WHERE CUISINE='Italian' AND PRICE='$$$$';

-- SELECT ALL RECORDS WHERE NAME CONTAINS CANDY
SELECT * FROM NOMNOM WHERE NAME LIKE '%candy%';

-- SELECT ALL RECORDS WHERE SECOND LETTER OF NAME IS i
SELECT * FROM NOMNOM WHERE NAME LIKE '_i%';

-- SELECT ALL RECORS WHERE NEIGHBOURHOOD SHOULD BE MIDTOWN DOWNTOWN OR CHINATOWN
SELECT * FROM NOMNOM WHERE NEIGHBOURHOOD='Midtown' or NEIGHBOURHOOD='Downtown' or NEIGHBOURHOOD='Chinatown';

-- SELECT ALL RECORS WHERE NEIGHBOURHOOD SHOULD BE MIDTOWN DOWNTOWN OR CHINATOWN NOT USING OR
SELECT * FROM NOMNOM WHERE NEIGHBOURHOOD IN('Midtown','Downtown','Chinatown');

-- SELECT TOP FOUR RECORDS WITH DECREASING ORDER OF REVIEW RATINGS
SELECT * FROM NOMNOM
ORDER BY REVIEW DESC
LIMIT 4;